// This is automatically generated by the Tiger compiler.
// Do NOT modify!

// structures
struct BinarySearch
{
  struct BinarySearch_vtable *vptr;
};
struct BS
{
  struct BS_vtable *vptr;
  int* number;
  int size;
};
// vtables structures
struct BinarySearch_vtable
{
};

struct BS_vtable
{
  int (*Start)();
  int (*Search)();
  int (*Div)();
  int (*Compare)();
  int (*Print)();
  int (*Init)();
};


// methods
int BS_Start(struct BS * this, int sz)
{
  int aux01;
  int aux02;
  struct BS * x_1;
  struct BS * x_2;
  struct BS * x_3;
  struct BS * x_4;
  struct BS * x_5;
  struct BS * x_6;
  struct BS * x_7;
  struct BS * x_8;
  struct BS * x_9;
  struct BS * x_10;

  this->aux01 = this->aux01;
  this->aux02 = this->aux02;
  if ((x_3=this, x_3->vptr->Search(x_3, 8)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_4=this, x_4->vptr->Search(x_4, 19)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_5=this, x_5->vptr->Search(x_5, 20)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_6=this, x_6->vptr->Search(x_6, 21)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_7=this, x_7->vptr->Search(x_7, 37)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_8=this, x_8->vptr->Search(x_8, 38)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_9=this, x_9->vptr->Search(x_9, 39)))
    System_out_println (1);
  else
    System_out_println (0);
  if ((x_10=this, x_10->vptr->Search(x_10, 50)))
    System_out_println (1);
  else
    System_out_println (0);
  return 999;
}
int BS_Search(struct BS * this, int num)
{
  int bs01;
  int right;
  int left;
  int var_cont;
  int medium;
  int aux01;
  int nt;
  struct BS * x_11;
  struct BS * x_12;
  struct BS * x_13;

  this->aux01 = this->aux01;
  this->bs01 = this->bs01;
  this->right = this->right;
  this->right = this->right;
  this->left = this->left;
  this->var_cont = this->var_cont;
  while(var_cont)
    {
      this->medium = this->medium;
      this->medium = this->medium;
      this->aux01 = this->aux01;
      if (num < aux01)
        this->right = this->right;
      else
        this->left = this->left;
      if ((x_12=this, x_12->vptr->Compare(x_12, aux01, num)))
        this->var_cont = this->var_cont;
      else
        this->var_cont = this->var_cont;
      if (right < left)
        this->var_cont = this->var_cont;
      else
        this->nt = this->nt;
    }
  if ((x_13=this, x_13->vptr->Compare(x_13, aux01, num)))
    this->bs01 = this->bs01;
  else
    this->bs01 = this->bs01;
  return bs01;
}
int BS_Div(struct BS * this, int num)
{
  int count01;
  int count02;
  int aux03;

  this->count01 = this->count01;
  this->count02 = this->count02;
  this->aux03 = this->aux03;
  while(count02 < aux03)
    {
      this->count01 = this->count01;
      this->count02 = this->count02;
    }
  return count01;
}
int BS_Compare(struct BS * this, int num1, int num2)
{
  int retval;
  int aux02;

  this->retval = this->retval;
  this->aux02 = this->aux02;
  if (num1 < num2)
    this->retval = this->retval;
  else
    if (!(num1 < aux02))
      this->retval = this->retval;
    else
      this->retval = this->retval;
  return retval;
}
int BS_Print(struct BS * this)
{
  int j;

  this->j = this->j;
  while(j < this->size)
    {
      System_out_println (this->number[j]);
      this->j = this->j;
    }
  System_out_println (99999);
  return 0;
}
int BS_Init(struct BS * this, int sz)
{
  int j;
  int k;
  int aux02;
  int aux01;

  this->size = this->size;
  this->number = this->number;
  this->j = this->j;
  this->k = this->k;
  while(j < this->size)
    {
      this->aux01 = this->aux01;
      this->aux02 = this->aux02;
      this->number[j] = aux01 + aux02;
      this->j = this->j;
      this->k = this->k;
    }
  return 0;
}

// vtables
struct BinarySearch_vtable BinarySearch_vtable_ = 
{
};

struct BS_vtable BS_vtable_ = 
{
  BS_Start,
  BS_Search,
  BS_Div,
  BS_Compare,
  BS_Print,
  BS_Init,
};


// main method
int Tiger_main ()
{
  struct BS * x_0;
  System_out_println ((x_0=((struct BS*)(Tiger_new (&BS_vtable_, sizeof(struct BS)))), x_0->vptr->Start(x_0, 20)));
}




