// This is automatically generated by the Tiger compiler.
// Do NOT modify!
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void *Tiger_new (void *vtable, int size);
int System_out_println (int i);

// structures
struct Sum
{
  struct Sum_vtable *vptr;
};
struct Doit
{
  struct Doit_vtable *vptr;
};
// vtables structures
struct Sum_vtable
{
};

struct Doit_vtable
{
  int (*doit)();
};


// vtable ptr and init method decls
struct Sum_vtable Sum_vtable_;
struct Sum_vtable * Sum_vtable_ptr;
void* get_Sum_vtable_();
struct Doit_vtable Doit_vtable_;
struct Doit_vtable * Doit_vtable_ptr;
void* get_Doit_vtable_();

// methods
int Doit_doit(struct Doit * this, int n)
{
  int sum;
  int i;

  i = 0;
  sum = 0;
  while(i < n)
    {
      sum = sum + i;
      i = i + 1;
    }
  return sum;
}

// vtable get methods
void* get_Sum_vtable_(){
  if(Sum_vtable_ptr== NULL){
    struct Sum_vtable temp = 
      {
      };
    memcpy(&Sum_vtable_, &temp, sizeof(temp));
    int equal = (int)memcmp(&Sum_vtable_, &temp, sizeof(temp));
    if(equal != 0){
      printf("Memory copy error: buffer polluted\n");
      exit(-2);
    }
    Sum_vtable_ptr = &Sum_vtable_;
  }
  return (void*)(Sum_vtable_ptr);
}

void* get_Doit_vtable_(){
  if(Doit_vtable_ptr== NULL){
    struct Doit_vtable temp = 
      {
        Doit_doit,
      };
    memcpy(&Doit_vtable_, &temp, sizeof(temp));
    int equal = (int)memcmp(&Doit_vtable_, &temp, sizeof(temp));
    if(equal != 0){
      printf("Memory copy error: buffer polluted\n");
      exit(-2);
    }
    Doit_vtable_ptr = &Doit_vtable_;
  }
  return (void*)(Doit_vtable_ptr);
}


// main method
int Tiger_main ()
{
  struct Doit * x_0;
  System_out_println ((x_0=((struct Doit*)(Tiger_new (get_Doit_vtable_(), sizeof(struct Doit)))), x_0->vptr->doit(x_0, 101)));
  return 0;
}




